Biding_store/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from market import classviews
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('account/', user_views.account, name='account'),
    path('address/', user_views.address, name='address'),
    path('myitems/', classviews.UserProductWonListView, name='items-won'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view
             (
             template_name='users/password_reset.html'
         ),
         name='password_reset'
         ),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view
             (
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'
         ),
    path('', include('market.urls')),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view
             (
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view
             (
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
    path('', include('market.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
import market.views
from . import classviews

urlpatterns = [
	path('home/', classviews.ProductListView.as_view(), name='market-home'),
	path('post/agriculture/', classviews.AgriProdListView.as_view(), name='agri-product'),
	path('product-detail/<int:pk>/', market.views.bid_information_view, name='product-detail'),
	path('post/new/', classviews.ProductCreateView.as_view(), name='product-create'),
	path('post/viewproduct/', classviews.ProductListView.as_view(), name='view-product'),
	path('post/bidderlist/<int:pk>/', classviews.BidderListView.as_view(), name="bidder-list"),
	path('post/createbid/', market.views.bid_create, name="create-bid"),
	path('post/<int:pk>/delete/', classviews.ProductDeleteView.as_view(), name='product-delete'),
	path('post/<int:pk>/update/', classviews.ProductUpdateView.as_view(), name='product-update'),
	path('user/<user_name>/', classviews.UserProductListView.as_view(), name='user-posts'),
	path('', market.classviews.about, name='about'),
	path('get_bidding_time/', market.views.get_bidding_time, name='get_bidding_time'),
	path('pay/<int:pk>', market.views.make_pay, name='pay'),
	path('reset_bid_time/', market.views.reset_bid_time, name='reset_bid_time')
]

market/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# from django.db.backends.sqlite3.base import DatabaseWrapper
# DatabaseWrapper.data_types = DatabaseWrapper._data_types


class Product(models.Model):
    title = models.CharField("Input the title of the Item you are selling", max_length=30)
    description = models.TextField("Input some description of the item", null=False, default='')
    image = models.ImageField("Let the buyer see what you are selling, upload a picture",
                              null=False, default='', upload_to='commodity_pics')
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    CATEGORY = (
        ('Relic', 'Relic'),
        ('Agriculture', 'Agriculture')
    )
    TYPE = (
        ('Painting', 'Painting'),
        ('Sculpture', 'Sculpture'),
        ('Book', 'Book'),
        ('Instrument', 'Instrument'),
        ('Milk', 'Milk'),
        ('Tea', 'Tea'),
        ('Maize', 'Maize')
    )
    category = models.CharField("Choose product category", max_length=100, default='Gen', choices=CATEGORY)
    type = models.CharField("Choose product type", max_length=100, default='Painting', choices=TYPE)
    price = models.IntegerField("What is the least/(unit) price you are selling your item for?")
    sell_on = models.DateTimeField(default=timezone.now)
    BID_TIME = (
        ('5', '5 minutes'),
        ('10', '10 minutes'),
        ('30', '30 minutes'),
        ('60', '1 Hour'),
        ('720', '1 month'),
        ('1440', '2 months'),
        ('2160', '3 Months')
    )
    live_time = models.CharField("How long should your item stay in the auction table?", max_length=20, default='5',
                                 choices=BID_TIME
                                 )
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='2')

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})


class Bidder(models.Model):
    numeric = RegexValidator(r'^[0-9]*$', 'Only numeric are allowed.')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    bid_amount = models.CharField(max_length=255, validators=[numeric])
    Status = (
        ('PENDING', '0'),
        ('WINNER', '1'))

    bid_status = models.CharField(max_length=20, choices=Status, default='PENDING')

    def _unicode_(self):
        return str(self.user_name)

market/forms.py
from django import forms
from market.models import Product
from django.utils import timezone


class BidForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ['price']

market/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render

from .models import *


# from .render import Render


def get_bid_info_context(pk):
    bidders = Bidder.objects.filter(product_id=pk).order_by('-created')[:6]
    product = Product.objects.get(id=pk)
    context = {'bidders': bidders, 'product': product}
    return context


def bid_information_view(request, pk):
    context = get_bid_info_context(pk)
    return render(request, 'market/product_detail.html', context)


def bid_create(request):
    if request.method == 'POST':
        p_id = request.POST.get('product_id')
        user_id = request.user
        b_amount = int(request.POST.get('bid_amount'))
        if int(b_amount) >= int(request.POST.get('minimum_price')):
            bids = Bidder.objects.filter(product_id=p_id, user_name=user_id)
            if bids:
                min_price = 0
                for bid in bids:
                    if int(bid.bid_amount) > min_price:
                        min_price = int(bid.bid_amount)
                if int(b_amount) >= int(min_price):
                    bid = Bidder.objects.filter(user_name=request.user)
                    if not bid:
                        Bidder.objects.filter(product_id=p_id).update(bid_status='PENDING')
                        product = Product.objects.filter(id=p_id).first()
                        bidder = Bidder.objects.create(user_name=request.user, product_id=product, bid_amount=b_amount,
                                                       bid_status='WINNER')
                        bidder.save()
                        context = get_bid_info_context(p_id)
                        # bids.update(bid_status='PENDING')
                        return render(request, 'market/product_detail.html', context)
                    Bidder.objects.filter(product_id=p_id).update(bid_status='PENDING')
                    bid.update(bid_amount=b_amount, bid_status='WINNER')
                    context = get_bid_info_context(p_id)
                    return render(request, 'market/product_detail.html', context)
                Bidder.objects.filter(product_id=p_id).update(bid_status='PENDING')
                context = get_bid_info_context(p_id)
                messages.error(request, "bid price should be more than Highest bid amount")
                return render(request, 'market/product_detail.html', context)
            product = Product.objects.filter(id=p_id).first()
            bidder = Bidder.objects.create(user_name=request.user, product_id=product, bid_amount=b_amount,
                                           bid_status='WINNER')
            bidder.save()
            context = get_bid_info_context(p_id)
            return render(request, 'market/product_detail.html', context)
        context = get_bid_info_context(p_id)
        messages.error(request, "bid price should be more than Highest Bid amount")
        return render(request, 'market/product_detail.html', context)


def get_bidding_time(request):
    product_id = request.GET['product_id']
    data = Product.objects.get(id=product_id)
    sell_on = data.sell_on
    bid_time = data.live_time
    time_data = {
        'sell_on': sell_on,
        'bid_time': bid_time
    }
    return JsonResponse(time_data)


def reset_bid_time(request):
    product_id = request.GET['product_id']
    Product.objects.filter(id=product_id).update(live_time=0)
    return JsonResponse({'msg': 'done'})


def make_pay(request, pk):
    context = get_bid_info_context(pk)
    return render(request, 'users/payment_details.html', context)


def get_bidding_time(request):
    product_id = request.GET['product_id']
    data = Product.objects.get(id=product_id)
    sell_on = data.sell_on
    bid_time = data.live_time
    time_data = {
        'sell_on': sell_on,
        'bid_time': bid_time
    }
    return JsonResponse(time_data)


def reset_bid_time(request):
    product_id = request.GET['product_id']
    Product.objects.filter(id=product_id).update(live_time=0)
    return JsonResponse({'msg': 'done'})

market/templates/market/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:color="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>AuctionIt</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css' %}">
	<link rel="stylesheet" type="text/css" href="/market/static/css/main.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse fixed-top">
	<div class="container-fluid">
		<div class="navbar-header ">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'about' %}">AuctionIt</a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<li class=""><a href="{% url 'market-home' %}">Relics</a></li>
                <li class=""><a href="{% url 'agri-product' %}">Agriculture</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'product-create' %}">Sell</a></li>
					<li><a href="{% url 'profile' %}">Profile</a></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li><a href="{% url 'logout' %}">Logout</a></li>
						{% else %}
						<li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
						<li><a href="{% url 'register' %}"><span class="glyphicon "></span> Register</a></li>
					</ul>
				{% endif %}
		</div>
	</div>
</nav>
<div class="carts container">
	<h1 align="center">Features</h1>
	<div class="col-md-4 col-xs-12 text-center">
		<div class="icon">
			<span class="glyphicon glyphicon-shopping-cart"></span>
			<h4><b>Select the items from the list. Bid against both time and others</b></h4>
		</div>
	</div>
	<div class="col-xs-12 col-md-4 text-center">
		<div class="icon">
			<span class="glyphicon glyphicon-hourglass"></span>
			<h4><b>Every item has got its own time limit. Once the time limit has been reached, bidding is closed</b>
			</h4>
		</div>
	</div>
	<div class="col-xs-12 col-md-4 text-center">
		<div class="icon">
			<span class="glyphicon glyphicon-envelope"></span>
			<h4><b>The bidder with highest bidding amount is notified and also the seller</b></h4>
		</div>
	</div>
</div>
<div class="container-fluid">
	<article>
		<div class="media container ">
			<div class="container">
				<H2>The bidding process:</H2>
				<ol>
					<li> Register as a user (A user can buy or sell on the platform)</li>
					<li>Log in using the registered details.</li>
					<li>check the product catalog and note the time your desired item goes live on auction</li>
					<li>come back at this time adn place your bid</li>
					<li>Monitor the various bids placed and adjust accordingly. (every item will be on auction for 5
						minutes tops)
					</li>
					<li>Bid on as many items as you like. (On any bid that you win, The item will eb available for you
						to pay within 24 hours.)
					</li>
					<li> All won bids will be on you profile page on the items won section.</li>
				</ol>
			</div>
		</div>
	</article>
</div>
<br>
<hr>
<br>
<br><br>
<footer class="container-fluid text-center" style="background: orangered;">
	<p> © 2019 AUCTIONIT. All Rights Reserved | Design by <a href="#"> Apeiron Analytics</a></p>
</footer>
</body>
</html>

market/templates/market/bidder_list.html
{% extends 'market/navigation_part.html' %}
{% load static %}
{% block content %}
	<hr>
	<div class="media container">
		{% if bidder_list %}
			{#        <a class="article-title" >Available Bids for the item and BidList for {{ product_list.title }}</a><br>#}
			<table class="table table-hover table-striped">
				<thead>
				<tr bgcolor="#5f9ea0">
					<th>Bidder's Name</th>
					<th>Bid Amount</th>
					<th>Bid time</th>
				</tr>
				</thead>
				<tbody>
				{% for bid in bidder_list %}
					<tr>
						<td>{{ bid.user_name }}</td>
						<td>Ksh. {{ bid.bid_amount }}</td>
						<td>{{ bid.created }}</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		{% else %}
			<h2 style="text-align: center; color: black">No bids!!</h2>
		{% endif %}
		<div>
			<a href="{% url 'market-home' %}">Go Back Home</a>
		</div>
	</div>
	<br>
	<br><br> <br><br>  <br><br><br><br> <br><br> <br><br> <br><br>
{% endblock %}

market/templates/market/home.html
{% load static %}
<script src="{% static 'javascript/func.js' %}"></script>
<!DOCTYPE html>
<html lang="en">
<head>
	<title>AuctionIt</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dropdowns.css' %}">
	<link rel="stylesheet" type="text/css" href="/market/static/css/main.css">



</head>
<body onload="startTime()">
<div class="jumbotron">
	<div class=" text-center">
		<h1>AuctionIt</h1>
		<p>come, buy, live</p>
		<h3>
			<div id="txt"></div>
		</h3>
	</div>
</div>
<nav class="navbar navbar-inverse fixed-top">
	<div class="container-fluid">
		<div class="navbar-header ">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'about' %}">AuctionIt</a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<li class=""><a href="{% url 'market-home' %}">Relics</a></li>
                <li class=""><a href="{% url 'agri-product' %}">Agriculture</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'product-create' %}">Sell</a></li>
					<li><a href="{% url 'profile' %}">Profile</a></li>
                    </li>
					<li><a href="{% url 'about' %}">Contact</a></li>
                    </ul>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="{% url 'logout' %}">Logout</a></li>
						{% else %}
						<li><a href="#"><span class="glyphicon glyphicon-user"></span> Login</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Register</a></li>
					</ul>
				{% endif %}
		</div>
	</div>
</nav>
<div class="container-fluid">
	{% block content %}
		{% for post in object_list %}

			<article>
				<div class=" w-full sm:w-1/1 md:w-1/2 flex flex-col p-1">
					{#    <div class="row">#}
					<div class="col-sm-4">
						<div class="panel panel-primary">
							<div class="panel-heading">
								<a class="btn" href="{% url 'product-detail' post.id %}">
									{{ post.title }}, {{ post.type }} sold by {{ post.seller }} </a>
							</div>
							<div class="panel-body "><a href="{% url 'product-detail' post.id %}">
								<img src="{{ post.image.url }}"
								     class="sell-img img-responsive" style="width:100%" alt="Image"> </a>
								<div class="panel-footer">going live on: {{ post.sell_on|date:"F d, H:i" }}</div>
								<div class="panel-footer">
									<a class="btn btn-dark mbr-3" href="{% url 'product-detail' post.id %} ">
										<b> More details </b> </a></div>
							</div>
						</div>
					</div>
			</article>
		{% endfor %}
	{% endblock content %}
</div>
<hr>
<div class="container-fluid">
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-5" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-5" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-5" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-info mb-5" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-5" href="?page={{ page_obj.next_page_number }}">Next</a>
			<a class="btn btn-outline-info mb-5" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}
	{% endif %}
</div>
</body>
<hr>
<footer class="container-fluid text-center" style="background: black; color: #f7f7f7; padding-top: 1%">
	<p> © 2019 AUCTIONIT. All Rights Reserved | Design by <a href="#"> Apeiron Analytics</a></p>
</footer>
<script>
    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();
        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('txt').innerHTML =
            h + ":" + m + ":" + s;
        var t = setTimeout(startTime, 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i
        }
        ;  // add zero in front of numbers < 10
        return i;
    }
    $('.dropdown-toggle').dropdown()
</script>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
</script>
</html>

market/templates/market/navigation_part.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>AuctionIt</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<script src="/market/static/javascript/func.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="/market/static/css/main.css">
	<link rel="stylesheet" type="text/css" href="/market/static/css/profiles.css">
</head>
<body onload="timer2()">
<nav class="navbar navbar-inverse fixed-top">
	<div class="container-fluid">
		<div class="navbar-header ">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'about' %}">AuctionIt</a>
		</div>
		<ul class="nav navbar-nav">
			<li class=""><a href="{% url 'market-home' %}">Relics</a></li>
            <li class=""><a href="{% url 'agri-product' %}">Agriculture</a></li>
			{% if user.is_authenticated %}
				<li><a href="{% url 'product-create' %}">Sell</a></li>
				<li><a href="{% url 'profile' %}">Profile</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'logout' %}">Logout</a></li>
					{% else %}
					<li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
					<li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-shopping-cart"></span>
						Register</a></li>
				</ul>
			{% endif %}
	</div>
</nav>
<div class="container-fluid" style="background: darkslategrey; align-content: center; color: red; font-size: larger ">
	<div style="background: #FFFFFF; text-align: center; width: inherit;">
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tag }}">
				{{ message }}
			{% endfor %}
		{% endif %}
		</div>
	</div>
</div>
{% block content %}
{% endblock %}
<footer class="container-fluid text-center" style="background: black; padding-top: 1%; color: #FFFFFF">
	<p> © 2019 AUCTIONIT. All Rights Reserved | Design by <a href="#"> Apeiron Analytics</a></p>
</footer>
</body>
</html>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous">#}
{#</script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/core.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
</script>
{% load static %}
<script src="{% static 'javascript/func.js' %}" type="text/javascript"></script>

market/templates/market/product_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>AuctionIt</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="/market/static/css/main.css">
</head>
<nav class="navbar navbar-inverse fixed-top">
	<div class="container-fluid">
		<div class="navbar-header ">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'market-home' %}">AuctionIt</a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<li class="active"><a href="{% url 'market-home' %}">Home</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'product-create' %}">Sell</a></li>
					<li><a href="#">Ticket shop</a></li>
					<li><a href="{% url 'profile' %}">Profile</a></li>
					<li><a href="{% url 'about' %}">Contact</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="{% url 'logout' %}">Logout</a></li>
						{% else %}
						<li><a href="#"><span class="glyphicon glyphicon-user"></span> Login</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Register</a></li>
					</ul>
				{% endif %}
		</div>
	</div>
</nav>
<div class="container-fluid">
	{% block content %}
		<div class="content-section">
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Delete Product</legend>
					<h2>Are you sure you want to delete the Product? "{{ object.title }}</h2>
				</fieldset>
				<div class="form-group">
					<button class="btn-outline-danger" type="submit">Yes, Delete!</button>
					<a class="btn-outline-secondary" href="{% url 'product-detail' object.id %}"> No, cancel</a>
				</div>
			</form>
		</div>
	{% endblock content %}